# Generated by Django 2.2 on 2021-10-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PubMed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100000)),
                ('abstract', models.CharField(max_length=100000)),
            ],
        ),
    ]
